services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  backend-dev:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    restart: always
    environment:
      DATABASE_URL: postgres://user:password@db:5432/db
      RUST_LOG: debug
      TZ: Europe/Ljubljana
    volumes:
      - ./backend:/usr/src/backend
    command: cargo watch -x run
    depends_on:
      - db
    ports:
      - "8000:8000"

  backend-prod:
    image: tomlidobnik/backend:prod
    restart: always
    environment:
      DATABASE_URL: postgres://user:password@db:5432/db
      RUST_LOG: info
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./backend/.env:/app/.env:ro
      - ./backend/key.pem:/app/key.pem:ro
      - ./backend/cert.pem:/app/cert.pem:ro

  frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    restart: always
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    stdin_open: true
    tty: true
    command: npm run dev

  frontend-prod:
    image: tomlidobnik/frontend:prod
    restart: always
    ports:
      - "3000:3000"

volumes:
  db_data:

