services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  backend:
    build: ./backend
    restart: always
    environment:
      DATABASE_URL: postgres://user:password@db:5432/db
      RUST_LOG: info
    volumes:
      - ./backend:/usr/src/backend
    command: cargo watch -x run
    depends_on:
      - db
    ports:
      - "8000:8000"
  
  frontend:
    build: ./frontend
    restart: always
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    stdin_open: true
    tty: true
    command: npm run dev

volumes:
  db_data:

