FROM rust:slim

RUN apt-get update && apt-get install -y libpq-dev pkg-config && \
    cargo install cargo-watch && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/src/backend

COPY . .

CMD ["cargo", "watch", "-x", "run"]

