[project]
name = "projekt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pytorch-lightning",
    "torch",
    "torchvision",
    "PyYAML",
    "lightning>=2.6.0",
    "tensorboard>=2.20.0",
    "matplotlib>=3.10.8",
    "fastapi>=0.115.0",
    "uvicorn[standard]>=0.32.0",
    "python-multipart>=0.0.12",
    "pillow>=11.0.0",
    "requests>=2.32.5",
    "bcrypt>=4.1.0",
    "pyjwt>=2.8.0",
    "pydantic>=2.0.0",
    "python-dotenv>=1.0.0",
]
