name: Build and deploy

on:
  push:
    branches:
      - "develop"

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Make build.sh executable
        run: chmod +x ./build.sh

      - name: Run build script to build images
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: ./build.sh

      - name: Deploy to PI
        env:
          BACKEND_ENV_FILE: ${{ secrets.BACKEND_ENV_FILE }}
        run: |
          if [ ! -d "/home/pi/FERI-Digitalni-dvojcek" ]; then
            git clone git@github.com:tomlidobnik/FERI-Digitalni-dvojcek.git /home/pi/FERI-Digitalni-dvojcek
          fi

          cd /home/pi/FERI-Digitalni-dvojcek
          git switch develop
          git pull origin
          git reset --hard origin/develop

          cd ./backend
          echo "$BACKEND_ENV_FILE" > .env
          mkcert -install
          mkcert -key-file key.pem -cert-file cert.pem tom.thehomeserver.net
          cd ..

          docker pull tomlidobnik/backend:prod
          docker pull tomlidobnik/frontend:prod

          docker-compose down
          docker-compose up -d --build db backend-prod frontend-prod

