name: Build and deploy

on:
  push:
    branches:
      - "develop"

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Make build.sh executable
        run: chmod +x ./build.sh

      - name: Run build script to build images
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: ./build.sh

      - name: Webhook
        uses: joelwmale/webhook-action@master
        with:
          url: ${{ secrets.WEBHOOK_URL }}
          headers: > 
            {
              "repository": "joelwmale/webhook-action",
              "X-Hub-Signature-256": "${{ secrets.WEBHOOK_SECRET }}"
            }

